---
- hosts: fms
  gather_facts: false
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3)
      register: output
      changed_when: output.stdout != ""
    - setup:
  roles:
#    Enable below if you wish to install a firewall (a very good idea)
#    - geerlingguy.firewall
#    Enable below if you wish to use Let's Encrypt SSL certificates (another good idea)
#    - geerlingguy.certbot
    - fms
#    If you've enabled Let's encrypt above, also enable this to update the certbot config
#    - fms-certbot
  become: true
