---
- name: Make sure the server is up to date
  become: true
  apt:
    autoclean: yes
    autoremove: yes
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Create a folder for the installer
  file:
    path: /tmp/fms
    state: directory

- name: Copy the installer to the host
  copy:
    src: "{{ role_path }}/files/{{ installer_filename }}"
    dest: "/tmp/fms/{{ installer_filename }}"

- name: Copy the license certificate
  copy:
    src: LicenseCert.fmcert
    dest: /tmp/fms/LicenseCert.fmcert

- name: Copy and populate the Assisted install file
  template:
    src: Assisted Install.txt.j2
    dest: /tmp/fms/Assisted Install.txt

- name: Run the installer
  apt:
    deb: "/tmp/fms/{{ installer_filename }}"
  become: true
  environment:
    FM_ASSISTED_INSTALL: "/tmp/fms"

- name: Install SSL certificate
  copy:
    content: "{{ ssl_cert }}"
    dest: /etc/ssl/certs/{{ fqdn }}.crt
    owner: root
    mode: 0700

- name: Install SSL key
  copy:
    content: "{{ ssl_key }}"
    dest: /etc/ssl/private/{{ fqdn }}.key
    owner: root
    mode: 0700

- name: Install Intermediary certificate
  copy:
    content: "{{ intermediary_cert }}"
    dest: /etc/ssl/certs/{{ fqdn }}.chain.crt
    owner: root
    mode: 0700

# Using own certificate
- name: Use fmsadmin to import the SSL certificate
  shell: fmsadmin certificate import /etc/ssl/certs/{{ fqdn }}.crt --keyfile /etc/ssl/private/{{ fqdn }}.key --intermediateCA /etc/ssl/certs/{{ fqdn }}.chain.crt -y -u "{{ admin_user }}" -p "{{ admin_password }}"
  become: true

# Using Certbot
- name: Use fmsadmin to import the SSL certificate
  shell: fmsadmin certificate import /etc/letsencrypt/archive/{{ fqdn }}/cert1.pem --keyfile /etc/letsencrypt/archive/{{ fqdn }}/privkey1.pem --intermediateCA /etc/letsencrypt/archive/{{ fqdn }}/chain1.pem -y -u "{{ admin_user }}" -p "{{ admin_password }}"
  become: true

- name: Remove the installation directory
  file:
    path: /tmp/fms
    state: absent

- name: Copy and populate the .xfac.json to stop us being asked to import an SSL cert
  template:
    src: xfac.json.j2
    dest: '/opt/FileMaker/FileMaker Server/Admin/FAC/config/.xfac.json'
    owner: fmserver
    group: fmsadmin
    mode: 0775

- name: Close the sample file
  shell: "fmsadmin close {{ database_location }}Sample/FMServer_Sample -f -y -u {{ admin_user }} -p {{ admin_password }}"
  become: true

- name: Remove the sample file
  shell: "fmsadmin remove {{ database_location }}Sample/FMServer_Sample -f -y -u {{ admin_user }} -p {{ admin_password }}"
  become: true

- name: Configure the timezone
  template: src=timezone.j2 dest=/etc/timezone
  tags:
    - timezone

- name: More Configure the timezone
  file: src=/usr/share/zoneinfo/{{timezone}} dest=/etc/localtime state=link force=yes
  tags:
    - timezone

- name: Restart the server to apply permissions and the imported certificate
  reboot:
  become: true
